name: pg-unit-testing
on:
  # Triggers the workflow on push or pull request events 
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pgaux:
    runs-on: ubuntu-latest
    container: perl:latest
    steps:
      - uses: actions/checkout@v2
      - name: run a simple unit test
        run: |
          cpanm Data::Dump
          perl t/macros/pgaux.t
