name: pg-unit-testing
on:
  push:
  workflow_dispatch:

jobs:
  pgaux:
    runs-on: ubuntu-latest
    env:
      WEBWORK_ROOT: .
    container: perl:latest
    steps:
      - uses: actions/checkout@v2
      - name: unit test for PGauxiliaryFunctions.pl
        run: |
          cpanm Data::Dump
          prove t/macros/pgaux.t
